### ISSUE TITLE
Showing chat after deletion

### ISSUE THREAD

**Issue by Anitejjain** [Naman-K-Jaiswal/ConnVerse#20]
After deleting a chat in the chat section of the website, the left part correctly removes the chat, but the right part fails to reload, thereby retaining the chat information when it should display an empty section after deletion.

<img width="1470" alt="ChatDelete" src="https://github.com/Naman-K-Jaiswal/ConnVerse/assets/131655465/62faddb9-49c0-4452-9f6d-5b835fbe1b29">

**Comment by PKING1501** [comment]
Resolved
