### ISSUE TITLE
Text Overflow

### ISSUE THREAD

**Issue by Anitejjain** [Naman-K-Jaiswal/ConnVerse#21]
In the "Search members" section, when searching for members with large text descriptions in their profiles, an overflow issue occurs where the text extends beyond its designated area.

![Screenshot 2024-04-07 220544](https://github.com/Naman-K-Jaiswal/ConnVerse/assets/131655465/b52763d9-b210-4140-9d81-fcf8da45dc55)

**Comment by Harsh-Agrawal-425** [comment]
Thanks for pointing out. This issue has been Resolved!
