### ISSUE TITLE
Multiple same tags in blog

### ISSUE THREAD

**Issue by Anitejjain** [Naman-K-Jaiswal/ConnVerse#23]
When creating a new blog, the system should prevent the addition of the same tag multiple times as it is redundant and does not add any meaningful information.

![WhatsApp Image 2024-04-07 at 10 45 40 PM](https://github.com/Naman-K-Jaiswal/ConnVerse/assets/131655465/f6119866-648d-42d7-9385-74743baf94b4)

**Comment by Harsh-Agrawal-425** [comment]
Resolved!
